services:
  vaultwarden:
    image: 'vaultwarden/server:latest'
    container_name: vaultwarden
    restart: unless-stopped
    expose:
      - '80'
  #  ports:
  #    - '8000:80'
    volumes:
      - vw-data:/data
    environment:
      - TZ=Europe/Paris
    #  - LOG_FILE=/data/logs/vaultwarden.log

networks:
  default:
    name: infranet
    driver: bridge

volumes:
  vw-data: 
    name: vw-data
