services:
  postfix:
    image: 'juanluisbaptiste/postfix:latest'
    container_name: postfix
    restart: unless-stopped
    expose:
      - '80'
  #  ports:
  #    - '8000:80'
    volumes:
      - pf-data:/data
    environment:
      - TZ=Europe/Paris
    #  - LOG_FILE=/data/logs/vaultwarden.log

networks:
  default:
    name: infranet
    driver: bridge

volumes:
  pf-data:
    name: pf-data
