services:
   app:
     image: 'adguard/adguardhome:latest'
     container_name: adguard
     restart: unless-stopped
     ports:
       - 53:53/tcp
       - 53:53/udp
       - 784:784/udp
       - 853:853/tcp
       - 3000:3000/tcp
       - 83:80/tcp
     volumes:
       - ad-work:/opt/adguardhome/work
       - ad-conf:/opt/adguardhome/conf

networks:
  default:
    name: infranet

volumes:
  ad-work:
    name: ad-work
  ad-conf:
    name: ad-conf
