services:
  portainer:
    image: 'portainer/portainer-ce:latest'
    container_name: portainer
    restart: unless-stopped
    expose:
#      - '8000'
      - '9443'
    volumes:
      - pt-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Paris  

networks:
  default:
    name: infranet
    driver: bridge

volumes:
  pt-data: 
    name: pt-data
