services:
  app:
    image: 'linuxserver/wireguard:latest'
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
#    expose:
#      - '51820/udp'
    ports:
      - 51820:51820/udp
    volumes:
      - wg-config:/config
      - /lib/modules:/lib/modules
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=vpn.moniika.tech
      - SERVERPORT=51820
      - PEERS=Achille,Xiaomi
#      - PEERS=2
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0,::0/0
      - LOG_CONFS=true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  default:
    name: infranet
    driver: bridge

volumes:
  wg-config: 
    name: wg-config
